Fix pack upload

diff --git a/.github/workflows/upload-artifacts.yml b/.github/workflows/upload-artifacts.yml
--- a/.github/workflows/upload-artifacts.yml
+++ b/.github/workflows/upload-artifacts.yml
@@ -56,10 +56,16 @@ jobs:
           token_format: 'access_token'
           workload_identity_provider: ${{ secrets.workload_identity_provider }}
           service_account: ${{ secrets.service_account }}
-      - name: Upload Packs to Artifacts Server
-        run : |
+      - if: inputs.storage_provider != ''
+        name: Upload Packs to Artifacts Server
+        run: |
+          if [ ${BUCKET_NAME} == '' ]; then
+            echo "BUCKET_NAME required."
+            exit 1
+          fi
           echo "Uploading packs ${PACK_NAMES}..."
           python $GITHUB_WORKSPACE/repository/build_related_scripts/bucket_upload_${STORAGE_PROVIDER}.py \
             --bucket_name "${BUCKET_NAME}" \
-            --branch_name "${PACK_NAMES}" \
+            --packs_directory "${ARTIFACTS_FOLDER}/uploadable_packs" \
+            --branch_name "${BRANCH_NAME}" \
             --verbose
